# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFontDatabase
from qt_material import apply_stylesheet
from encrypt_decrypt import EncrypterDecrypter
from encrypt_decrypt import IncorrectPasswordError
from master_ui import Ui_MainWindow


class Ui_LoginScreen(object):
    def startKeyWarden(self):
        self.main_window = QtWidgets.QMainWindow()
        self.main_window.setWindowIcon(QtGui.QIcon('resources/images/lockicon.png'))
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.main_window, self.master_pswd)
        self.main_window.show()

    def setupUi(self, LoginScreen):
        self.LOGINSCREEN = LoginScreen
        LoginScreen.setObjectName("LoginScreen")
        LoginScreen.setEnabled(True)
        LoginScreen.resize(350, 565)
        LoginScreen.setStyleSheet("")
        QFontDatabase.addApplicationFont('resources/fonts/Roboto.ttf')
        QFontDatabase.addApplicationFont('resources/fonts/Itim.ttf')
        self.centralwidget = QtWidgets.QWidget(LoginScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.pswdInputlineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.pswdInputlineEdit.setGeometry(QtCore.QRect(25, 200, 300, 35))
        self.pswdInputlineEdit.setObjectName("lineEdit")
        self.pswdInputlineEdit.setStyleSheet('font-family:Itim;font-size:16px;')
        self.pswdInputlineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.login_btn = QtWidgets.QPushButton(self.centralwidget)
        self.login_btn.setGeometry(QtCore.QRect(25, 435, 300, 50))
        self.login_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_btn.setObjectName("login_btn")
        self.forgot_pswd_btn = QtWidgets.QPushButton(self.centralwidget)
        self.forgot_pswd_btn.setGeometry(QtCore.QRect(25, 490, 300, 50))
        self.forgot_pswd_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.forgot_pswd_btn.setObjectName("forgot_pswd_btn")
        self.enter_your_pswd_label = QtWidgets.QLabel(self.centralwidget)
        self.enter_your_pswd_label.setGeometry(QtCore.QRect(25, 160, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.enter_your_pswd_label.setFont(font)
        self.enter_your_pswd_label.setObjectName("enter_your_pswd_label")
        self.show_pswd_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.show_pswd_checkbox.setGeometry(QtCore.QRect(25, 250, 125, 17))
        self.show_pswd_checkbox.setStyleSheet("font-size:12px;")
        self.show_pswd_checkbox.setObjectName("show_pswd_checkbox")
        self.lock_img_label = QtWidgets.QLabel(self.centralwidget)
        self.lock_img_label.setGeometry(QtCore.QRect(0, 20, 101, 101))
        self.lock_img_label.setText("")
        self.lock_img_label.setPixmap(QtGui.QPixmap("resources/images/thelock.png"))
        self.lock_img_label.setObjectName("lock_img_label")
        self.key_warden_label = QtWidgets.QLabel(self.centralwidget)
        self.key_warden_label.setGeometry(QtCore.QRect(90, 45, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.key_warden_label.setFont(font)
        self.key_warden_label.setObjectName("key_warden_label")
        LoginScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginScreen)
        QtCore.QMetaObject.connectSlotsByName(LoginScreen)

    def retranslateUi(self, LoginScreen):
        _translate = QtCore.QCoreApplication.translate
        LoginScreen.setWindowTitle(_translate("LoginScreen", "KeyWarden - Login"))
        self.login_btn.setText(_translate("LoginScreen", "Login"))
        self.forgot_pswd_btn.setText(_translate("LoginScreen", "Forgot Password?"))
        self.enter_your_pswd_label.setText(_translate("LoginScreen", "Enter your Master Password"))
        self.show_pswd_checkbox.setText(_translate("LoginScreen", "show password"))
        self.key_warden_label.setText(_translate("LoginScreen", "KeyWarden"))

        self.login_btn.clicked.connect(self.LoginFunction)

        self.show_pswd_checkbox.clicked.connect(self.showPswdFunction)

        self.forgot_pswd_btn.clicked.connect(self.ForgotPswdFunction)

    def LoginFunction(self):
        try:
            self.master_pswd = self.pswdInputlineEdit.text().encode()

            token = EncrypterDecrypter.read_json('resources/data/master_pswd.json')['token']
            EncrypterDecrypter.decrypt(self.master_pswd, token.encode())
            self.startKeyWarden()
            self.LOGINSCREEN.close()

        except IncorrectPasswordError:
            def incorrcetpopup():
                msgbox = QtWidgets.QMessageBox()
                msgbox.setWindowTitle("Incorrect Password")
                msgbox.setText("Incorrect password! Please check the password and try again.")
                msgbox.setIcon(QtWidgets.QMessageBox.Critical)
                msgbox.setWindowIcon(QtGui.QIcon('resources/images/lockicon.png'))
                msgbox.exec_()

            incorrcetpopup()

    def showPswdFunction(self):
        if self.show_pswd_checkbox.isChecked():
            self.pswdInputlineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
            return
        self.pswdInputlineEdit.setEchoMode(QtWidgets.QLineEdit.Password)

    def ForgotPswdFunction(self):
        dlg = QtWidgets.QMessageBox()
        dlg.setText("FUCK OFF. Password cannot be recovered.")
        dlg.setWindowTitle("FUCK YOU")
        dlg.setWindowIcon(QtGui.QIcon('resources/images/lockicon.png'))
        dlg.exec_()


# 01937C awesome


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    apply_stylesheet(app, 'my_dark_lightblue.xml')
    LoginScreen = QtWidgets.QMainWindow()

    LoginScreen.setWindowIcon(QtGui.QIcon('resources/images/lockicon.png'))
    ui = Ui_LoginScreen()
    ui.setupUi(LoginScreen)
    LoginScreen.show()
    sys.exit(app.exec_())
